
services:
  db:
    image: mysql:8.0.40
    container_name: course-container_1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Mysql
      MYSQL_DATABASE: course_app
    volumes:
      - course_vol:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d

volumes:
  course_vol:
